services:
  db:
    image: postgres:16
    container_name: ironmind-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ironmind
      POSTGRES_PASSWORD: ironmind_pw
      POSTGRES_DB: ironmind_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ironmind-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://ironmind:ironmind_pw@db:5432/ironmind_db
      FLASK_ENV: development
    ports:
      - "5432:5432"
    depends_on:
      - db

volumes:
  pgdata:
